#!/bin/sh


export KAMAL_REGISTRY_PASSWORD="$KAMAL_REGISTRY_PASSWORD"  # Берется из переменных окружения
export RAILS_MASTER_KEY=$(cat config/master.key)  # Автоматически из файла
export POSTGRES_PASSWORD="$DB_PASSWORD"  # Из переменных окружения
export DB_PASSWORD="$DB_PASSWORD"